load(
    "@rules_android//android:rules.bzl",
    "android_application",
    "android_binary",
    "android_library",
)

android_library(
    name = "basic_lib",
    srcs = ["BasicActivity.java"],
    manifest = "AndroidManifest.xml",
)
